sudo: required

language: node_js

node_js:
  - "6"

services:
  - docker

script:
  - npm run build
  - npm prune --production

after_success:
  - if [ "TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    export REPO=bellstrand/singorwing-api;
    docker build -f Dockerfile -t $REPO:$TRAVIS_TAG .;
    docker tag $REPO:$TRAVIS_TAG $REPO:$latest;
    docker push $REPO;
    fi

notifications:
  email: false
